name: StyLua
on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        ref: ${{ github.head_ref }}
    - name: Run StyLua
      uses: JohnnyMorganz/stylua-action@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: latest
        args: .
    - name: Push
      uses: stefanzweifel/git-auto-commit-action@master
      with:
        commit_message: "Formatting using StyLua"
